import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { FilledField, FormAnalysis } from '../types';

interface GeneratePdfOptions {
  formAnalysis: FormAnalysis | null;
  filledFields: FilledField[];
  langLabel: string;
  langCode: string;
  fileName?: string;
}

const NAVY = rgb(22 / 255, 47 / 255, 73 / 255);
const GOLD = rgb(201 / 255, 168 / 255, 76 / 255);
const INK = rgb(26 / 255, 26 / 255, 24 / 255);
const INK3 = rgb(107 / 255, 106 / 255, 100 / 255);
const CREAM = rgb(245 / 255, 244 / 255, 240 / 255);
const BORDER = rgb(221 / 255, 219 / 255, 211 / 255);
const WHITE = rgb(1, 1, 1);

export async function generateFilledFormPdf(options: GeneratePdfOptions): Promise<Uint8Array> {
  const { formAnalysis, filledFields, langLabel, langCode, fileName } = options;

  const doc = await PDFDocument.create();
  const fontRegular = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const PAGE_W = 595; // A4
  const PAGE_H = 842;
  const MARGIN = 50;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  const addPage = () => {
    page = doc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - MARGIN;
  };

  const ensureSpace = (needed: number) => {
    if (y - needed < MARGIN + 30) {
      // Draw footer on current page before adding new one
      drawFooter();
      addPage();
    }
  };

  const drawFooter = () => {
    const footerText = `Generated by ProntoVoila  |  ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`;
    const footerW = fontRegular.widthOfTextAtSize(footerText, 8);
    page.drawText(footerText, {
      x: PAGE_W / 2 - footerW / 2,
      y: 25,
      size: 8,
      font: fontRegular,
      color: INK3,
    });
  };

  // ── HEADER BAR ──
  page.drawRectangle({
    x: MARGIN,
    y: y - 60,
    width: CONTENT_W,
    height: 60,
    color: NAVY,
  });

  // Title in header
  const title = formAnalysis?.formTitleTranslated || 'Filled Form';
  page.drawText('ProntoVoila', {
    x: MARGIN + 18,
    y: y - 25,
    size: 16,
    font: fontBold,
    color: WHITE,
  });
  page.drawText(title, {
    x: MARGIN + 18,
    y: y - 45,
    size: 10,
    font: fontRegular,
    color: GOLD,
  });

  // Language badge on right
  const langText = `${langLabel} (${langCode})`;
  const langW = fontRegular.widthOfTextAtSize(langText, 9);
  page.drawText(langText, {
    x: MARGIN + CONTENT_W - langW - 18,
    y: y - 38,
    size: 9,
    font: fontRegular,
    color: rgb(1, 1, 1),
  });

  y -= 80;

  // ── FORM INFO ──
  if (formAnalysis) {
    // Original title
    page.drawText('Original form:', {
      x: MARGIN,
      y,
      size: 9,
      font: fontRegular,
      color: INK3,
    });
    page.drawText(formAnalysis.formTitleOriginal, {
      x: MARGIN + 75,
      y,
      size: 9,
      font: fontBold,
      color: INK,
    });
    y -= 16;

    // Source file
    if (fileName) {
      page.drawText('Source file:', {
        x: MARGIN,
        y,
        size: 9,
        font: fontRegular,
        color: INK3,
      });
      page.drawText(fileName, {
        x: MARGIN + 75,
        y,
        size: 9,
        font: fontRegular,
        color: INK,
      });
      y -= 16;
    }

    // Detected language
    page.drawText('Form language:', {
      x: MARGIN,
      y,
      size: 9,
      font: fontRegular,
      color: INK3,
    });
    page.drawText(formAnalysis.detectedLanguageLabel, {
      x: MARGIN + 75,
      y,
      size: 9,
      font: fontRegular,
      color: INK,
    });
    y -= 24;
  }

  // Divider
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: MARGIN + CONTENT_W, y },
    thickness: 1,
    color: BORDER,
  });
  y -= 24;

  // ── SECTION HEADER ──
  page.drawText('FILLED FORM DATA', {
    x: MARGIN,
    y,
    size: 10,
    font: fontBold,
    color: NAVY,
  });
  y -= 20;

  // ── FIELD ROWS ──
  const LABEL_W = 160;
  const VALUE_X = MARGIN + LABEL_W + 10;
  const VALUE_W = CONTENT_W - LABEL_W - 10;

  for (const field of filledFields) {
    // Calculate value text and wrapping
    const valueText = field.skipped ? '—  (not provided)' : (field.value || '—');
    const valueLines = wrapText(valueText, fontRegular, 10.5, VALUE_W - 20);
    const rowHeight = Math.max(36, 16 + valueLines.length * 14 + 10);

    ensureSpace(rowHeight + 6);

    const rowTop = y;

    // Background for the row
    page.drawRectangle({
      x: MARGIN,
      y: rowTop - rowHeight,
      width: CONTENT_W,
      height: rowHeight,
      color: CREAM,
    });

    // Gold left accent bar for filled values
    if (!field.skipped && field.value) {
      page.drawRectangle({
        x: VALUE_X - 4,
        y: rowTop - rowHeight + 4,
        width: 2.5,
        height: rowHeight - 8,
        color: GOLD,
      });
    }

    // Field label
    page.drawText(field.label.toUpperCase(), {
      x: MARGIN + 12,
      y: rowTop - 16,
      size: 8.5,
      font: fontBold,
      color: INK3,
    });

    // Field value (possibly multi-line)
    const valueColor = field.skipped ? INK3 : INK;
    const valueFont = field.skipped ? fontRegular : fontBold;
    valueLines.forEach((line, i) => {
      page.drawText(line, {
        x: VALUE_X + 8,
        y: rowTop - 16 - i * 14,
        size: 10.5,
        font: valueFont,
        color: valueColor,
      });
    });

    y -= rowHeight + 6;
  }

  // ── FOOTER ──
  drawFooter();

  return doc.save();
}

/** Wrap text to fit within a given pixel width. */
function wrapText(
  text: string,
  font: { widthOfTextAtSize: (text: string, size: number) => number },
  fontSize: number,
  maxWidth: number
): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const testWidth = font.widthOfTextAtSize(testLine, fontSize);
    if (testWidth > maxWidth && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines.length > 0 ? lines : [''];
}
